config/routes.rb
Rails.application.routes.draw do
  root to: 'enter#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: 'home#index'
  get 'introduce', to: 'introduce#index'
  get 'swallowing', to: 'swallowing#index'
  get 'aspiration', to: 'aspiration#index'
  get 'food', to: 'food#index'
  get 'toromi', to: 'toromi#index'
  get 'quiz', to: 'quiz#index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    home_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

end

app/controllers/aspiration_controller.rb
class AspirationController < ApplicationController

  def index  
  end

end

app/controllers/enter_controller.rb
class EnterController < ApplicationController

  def index  
  end

end

app/controllers/food_controller.rb
class FoodController < ApplicationController

  def index  
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index  
  end

end

app/controllers/introduce_controller.rb
class IntroduceController < ApplicationController

  def index  
  end

end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController

  def index  
  end

end

app/controllers/swallowing_controller.rb
class SwallowingController < ApplicationController

  def index  
  end

end

app/controllers/toromi_controller.rb
class ToromiController < ApplicationController
  
  def index  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aspiration_helper.rb
module AspirationHelper
end

app/helpers/enter_helper.rb
module EnterHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/introduce_helper.rb
module IntroduceHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/swallowing_helper.rb
module SwallowingHelper
end

app/helpers/toromi_helper.rb
module ToromiHelper
end

app/views/aspiration/index.html.erb
<%= render partial: 'modules/header' %>


<div class="aspiration__container"> 
  <div class="side-bar">
    <nav id="navbar-example3" class="navbar navbar-light bg-light position-fixed">
      <nav class="nav nav-pills flex-column">
        <a class="nav-link" href="#item-1">誤嚥とは</a>
        <nav class="nav nav-pills flex-column">
          <a class="nav-link ml-3 my-1" href="#item-1-1">誤嚥について</a>
        <a class="nav-link" href="#item-2">誤嚥の種類</a>
        <nav class="nav nav-pills flex-column">
          <a class="nav-link ml-3 my-1" href="#item-2-1">嚥下前誤嚥</a>
          <a class="nav-link ml-3 my-1" href="#item-2-2">嚥下中誤嚥</a>
          <a class="nav-link ml-3 my-1" href="#item-2-3">嚥下後誤嚥</a>
          <a class="nav-link ml-3 my-1" href="#item-2-4">不顕性誤嚥</a>
        </nav>
      </nav>
    </nav>
  </div>

  <div class="aspiration__main">
    <div data-spy="scroll" data-target="#navbar-example3" data-offset="0">
      <h4 id="item-1">誤嚥とは</h4>
      <p>
      誤嚥は、食べ物が飲み込みの失敗などによって声門（声を出す器官）より下に入ってしまう事を言います。<br>
      食べ物か気道の方に行ってしまった場合、しかし声門より上で食べ物を咳などで出せた場合は<br>「喉頭侵入（こうとうしんにゅう）」と言います。
      </p>

      <h5 id="item-1-1">誤嚥について</h5>
      <p>
      誤嚥は以下の４つに分類されます。<br>
      嚥下前誤嚥：嚥下反射（ごっくん）が起こる前の誤嚥<br>
      嚥下中誤嚥：嚥下反射（ごっくん）は起こるが、タイミングがずれた時に起こる誤嚥<br>
      嚥下後誤嚥：嚥下反射（ごっくん）が起こった後の誤嚥<br>
      不顕性誤嚥：ムセがない誤嚥<br>
      </p>

      <h4 id="item-2">誤嚥の種類</h4>
      <h5 id="item-2-1">嚥下前誤嚥</h5>
      <p>
      嚥下前誤嚥（えんげまえごえん）は、嚥下反射が起こる前の誤嚥です。<br>
      この誤嚥は喉の方に食物が流れ落ちているにも関わらず、嚥下反射が起こらない時に出ます。<br>
      主な原因は舌・口腔周囲の筋肉の筋力低下や知覚の低下などです。<br>
      ・筋力低下によって、口の中に食べ物が保持できない<br>
      ・食べ物が喉の方に流れてきても気づかない<br>
      等の理由が重なり、気道の方へ食物が入ってからムセが出現します。<br>
      </p>

      <h5 id="item-2-2">嚥下中誤嚥</h5>
      <p>
      嚥下反射は起こるが、タイミングがずれた時に起こる誤嚥のことです。<br>
      この誤嚥は様々な要因が考えられます。<br>
      ・加齢や脳血管疾患による知覚の低下<br>
      ・加齢による喉頭の下垂（喉仏を上げる筋力の低下）<br>
      ・飲み込みに関する筋肉の筋力低下<br>
      ・意識レベルの低下<br>
      ・るい痩（極端なやせ）による咽頭腔の拡大  など<br>
      飲み込んでいる様には見えるけど、嚥下後すぐにムセが出現します。
      </p>

      <h5 id="item-2-3">嚥下後誤嚥</h5>
      <p>
      嚥下後誤嚥はのどに残った食物が、気管の方へ流れ落ちることによって出現します。<br>
      主な要因は<br>
      ・嚥下に関する筋肉の筋力低下により、しっかりと飲み込みができていない<br>
      ⇨食道入口部（食道への入り口。基本は閉じており、嚥下の時のみ弛緩する）が開ききらない<br>
      ・梨状窩（りじょうか）に残っていた食物が気管へ流れ落ちる<br>
      （梨状窩：食道の入り口付近にある窪み。左右１つずつ存在する）
      </p>

      <h5 id="item-2-4">不顕性誤嚥</h5>
      <p>
      不顕性誤嚥（ふけんせいごえん）とはムセの無い誤嚥のことをいいます。<br>
      健康で、何も病気が無いに人は喉頭へ異物が入ってきた時にムセが起こります。<br>
      不顕性誤嚥では誤嚥しているにも関わらず、ムセがみられないため、肺炎や痰の増加、発熱<br>
      が起こって気付かれるケースが多いです。<br>
      この誤嚥の主な原因は知覚の低下が考えられます。
      </p>

      <p>
      ムセや誤嚥があったとしても、すぐに肺炎になるわけではありません。<br>
      本人の喀出能力、免疫、肺の自浄機能が勝っていた場合は肺炎にはなりません。<br>
      ただし、誤嚥はしない方が絶対に良いので、以下のことがあれば注意してみましょう<br>
      ・口の奥の方を触っても全くオエっとならない（咽頭反射がみられない）<br>
      ・舌の動きが緩慢で、話が聞き取りづらい<br>
      ・ずっと微熱が続いている<br>
      ・痰や咳が多い<br>
      ・食事が飲み込み辛そう、食事中に咳が出ている
      </p>
    </div>
      <%= link_to "ホームに戻る", home_path, class:"btn btn-primary" %>

  </div>

</div>

<script>
$('body').scrollspy({ target: '#navbar-example3' })
</script>

app/views/enter/index.html.erb
<div class="enter-container">
  <div class="enter-container__contents">
    <div class="enter-container__contents__title">
      <h1>Swallowing World</h1>
    </div>
    <div class="enter-container__contents__enter">
      <%= link_to "新規登録", new_user_registration_path, class: "enter-container__contents__enter__detail-left" %>
      <%= link_to "ログイン", new_user_session_path, class: "enter-container__contents__enter__detail-right" %>
    </div>
</div>

app/views/food/index.html.erb
<%= render partial: 'modules/header' %>

<div class="food__container"> 
  <div class="side-bar">
    <nav id="navbar-example3" class="navbar navbar-light bg-light position-fixed">
      <nav class="nav nav-pills flex-column">
        <a class="nav-link" href="#item-1">食べやすい食べ物と<br>食べにくい食べ物</a>
      <nav class="nav nav-pills flex-column">
        <a class="nav-link" href="#item-1">食べにくい食べ物</a>
        <nav class="nav nav-pills flex-column">
          <a class="nav-link ml-3 my-1" href="#item-1-1">硬いもの</a>
          <a class="nav-link ml-3 my-1" href="#item-1-2">噛むとばらけるもの</a>
          <a class="nav-link ml-3 my-1" href="#item-1-3">物性が均一でないもの</a>
          <a class="nav-link ml-3 my-1" href="#item-1-4">水分が少ないもの</a>
        <a class="nav-link" href="#item-2">食べやすい食べ物</a>
        <nav class="nav nav-pills flex-column">
          <a class="nav-link ml-3 my-1" href="#item-2-1">まとまりのあるもの</a>
          <a class="nav-link ml-3 my-1" href="#item-2-2">物性が均一であるもの</a>
          <a class="nav-link ml-3 my-1" href="#item-2-3">柔らかいもの</a>
        </nav>
      </nav>
    </nav>
  </div>

  <div class="food__main">
    <div data-spy="scroll" data-target="#navbar-example3" data-offset="0">
      <h4 id="item-1">食べやすい食べ物と食べにくい食べ物</h4>
      <p>
      嚥下障害がある方にとって食べやすいもの・食べにくいものがあるのはご存知でしょうか？<br>
      年始に「餅を喉につまらせる」というニュースが流れることがあるので、「餅は食べにくいもの」<br>
      と認知している方も多いと思います。<br>
      しかし、他にも食べにくい食材は多く存在します。<br>
      例を挙げながら説明していきます。
      </p>

      <h4 id="item-1">食べにくい食べ物</h4>
      <p>
      食べにくい食べ物について紹介します。<br>
      実は下に上げたものの他にも、誤嚥しやすいものが存在します。<br>
      それは「水」と「唾液」（水については次の章で説明します）<br>
      唾液は口の中に常にあります。<br>
      唾液は体温と同じ温度のため知覚しにくく、一度に飲み込む量も多く無いため、知らないうちに<br>
      誤嚥してしまうことがあります。<br>
      口腔内が汚れている状態の唾液を誤嚥すると、肺炎の原因になります。<br>
      食後・寝る前は必ず口腔内を清潔にするようにしましょう。
      </p>


      <h5 id="item-1-1">① 硬いもの</h5>
      <p>
      せんべいなどが挙げられます。<br>
      飲み込むためには粉々に砕いて、ペースト状にしなければなりません。<br>
      せんべいは硬く、歯が無いと砕いて食べることが困難になります。<br>
      飴は棒付きのものであれば大丈夫ですが、食べてもらう前に割れかけていないかを確認しましょう。<br>
      舐めて食べられない方（噛んで食べてしまう方）への提供はおすすめしません。<br>
      ゴボウなど、硬めの野菜はよく煮て柔らかくしてから提供するといいと思います。
      </p>

      <h5 id="item-1-2">噛むとばらけるもの</h4>
      <p>
      こちらは、せんべいやクッキーなどが挙げられます。<br>
      口の中でまとまりにくい食べ物は、喉の方へもばらけた状態で入ってしまうため、<br>
      飲み込みにくい食べ物となります。<br>
      意外ですが、寒天も食べにくい食べ物です。潰してみるとわかるのですが、<br>
      粉々にするとまとまってはくれません。<br>
      寒天はゼリーの代わりにはならないので注意しましょう。
      </p>

      <h5 id="item-1-3">物性が均一でないもの</h5>
      <p>
      こちらは高野豆腐やがんもどき、果汁の多い果物などが挙げられます。<br>
      とろみのない水はムセやすい食べ物の１つです。<br>
      高野豆腐などは噛むと水分が出てきます。つまり、口腔内には「高野豆腐」と「水分」が<br>
      存在することになります。<br>
      この２つは喉へ入った時の落ちる速度が違うため、ムセの原因となります。<br>
      噛むと汁が出てくる食事は避けましょう。果物は細かく潰してペースト状にし、とろみをつけると<br>
      食べることができる場合もあります。
      </p>


      <h5 id="item-1-4">水分が少ないもの</h5>
      <p>
      パン・海苔、あと先ほど述べたせんべい等が挙げられます。<br>
      水分の少ないものは口腔内に張り付いたり、食物を唾液と混ぜ合わせペースト状にすることが<br>
      難しくなります。<br>
      海苔の場合は口の中などに張り付いてしまうため危険です。<br>
      ご飯に何かのせないと食べにくい方もいらっしゃると思います。その際はふりかけではなく<br>
      練り梅や海苔の佃煮にしてください。<br>
      意外に食べにくいものがパンです。<br>
      病院や施設の朝食でパンは出ることが多いのですが、よく噛んでペースト状にできないと、<br>
      喉へ塊のまま落ちていってしまいます。<br>
      誤嚥というよりかは、窒息事故が起こりやすい食べ物という印象です。<br>
      あまり嚥下障害がある方へはパンはおすすめしないのですが、もしどうしても食べたいとの希望が<br>
      あるのであれば、パンを牛乳に浸した「パンがゆ」にしてみてはどうかと思います。
      </p>

      <h4 id="item-2">食べやすい食べ物</h4>
      <p>
      次に食べやすい食べ物を紹介します。<br>
      食べやすい食べ物は、基本的に食べにくい食べ物の反対の性質を持っていると考えてもらって<br>
      大丈夫です。
      </p>

      <h5 id="item-2-1">まとまりのあるもの</h5>
      <p>
      これは、バナナなどが挙げられます。<br>
      潰しても一つのまとまった形になり、ばらけないまま咽頭へ送ることが可能です。<br>
      食べにくいと思われがちなものですが、乳ボーロなど唾液で容易に溶けひとまとまりになる<br>
      おやつは飲み込みにくさを持っている方にとって食べやすいものとなります。
      </p>

      <h5 id="item-2-2">物性が均一であるもの</h5>
      <p>
      ゼリーやプリンなどのようなものが挙げられます。<br>
      物性が均一だと、先に何かが咽頭に流れ落ち、次に違うものが咽頭に流れ落ちるという<br>
      タイミングのずれを防ぐことができます。
      </p>

      <h5 id="item-2-3">柔らかいもの</h5>
      <p>
      こちらはお粥のようなものが挙げられますが、お粥はそのままだと食べにくい食べ物になります。<br>
      なぜかというと、唾液と混ざり合うと水っぽくなってしまうためです。<br>
      お粥を食べやすくするためには少しトロミを入れるといいかと思います。
      </p>
      <%= link_to "ホームに戻る", home_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>
<script>
$('body').scrollspy({ target: '#navbar-example3' })
</script>

app/views/home/index.html.erb
<%= render partial: 'modules/header' %>



<div class="container">

  <div id="carouselExampleIndicators" class="carousel slide mb-3" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
    </ol>
    <div class="carousel-inner">

      <div class="carousel-item active">
        <%= image_tag 'introduce', alt:"character", width: '100%', height: '400' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>自己紹介</h5>
          <p>このサイトの制作者自己紹介です</p>
        </div>
      </div>
      
      <div class="carousel-item">
        <%= image_tag 'swallow', alt:"character", width: '100%', height: '400' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>嚥下とは？</h5>
          <p>飲み込みについて詳しくみていきましょう</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'aspiration', alt:"character", width: '100%', height: '400' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>誤嚥とは？</h5>
          <p>色々な誤嚥の種類をみていきましょう！</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'food', alt:"character", width: '100%', height: '400' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>食べ物について</h5>
          <p>食べやすい食べ物・食べにくい食べ物について知りましょう</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'toromi', alt:"character", width: '100%', height: '400' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>とろみって何？</h5>
          <p>飲み込みにくさを解消させる「トロミ」について詳しく説明します</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'quiz', alt:"character", width: '100%', height: '400' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>クイズ！</h5>
          <p>現場で出会いそうなケースをクイズにしてみました</p>
        </div>
      </div>



  </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


  <div class="card-deck mb-3">
    <div class="card">
      <%= image_tag 'introduce', alt:"character", width: '100%', height: '200' %>
      <div class="card-body">
        <h5 class="card-title">自己紹介</h5>
        <p class="card-text">このサイトの制作者自己紹介とサイト紹介です。<br>今後、病院で働いていた時に思っていたことなど、書くことができる範囲でこちらに書いていこうかと思います。</p>
        <%= link_to "Go to Next Page!", introduce_path, class:"btn btn-primary"%>

      </div>
    </div>
    <div class="card">
      <%= image_tag 'swallow', alt:"character", width: '100%', height: '200' %>
      <div class="card-body">
        <h5 class="card-title">嚥下とは？</h5>
        <p class="card-text">飲み込みは５つの場面に分けて考えられることがあります。<br>その５つを詳しく見ていきましょう！</p>
        <%= link_to "Go to Next Page!", swallowing_path, class:"btn btn-primary"%>
      </div>
    </div>
    <div class="card">
      <%= image_tag 'aspiration', alt:"character", width: '100%', height: '200' %>
      <div class="card-body">
        <h5 class="card-title">誤嚥とは？</h5>
        <p class="card-text">誤嚥（食べ物などが誤って肺に入ること）には種類があります。色々な種類の誤嚥を見ていきましょう！</p>
        <%= link_to "Go to Next Page!", aspiration_path, class:"btn btn-primary"%>
      </div>
    </div>
  </div>

  <div class="card-deck mb-3">
    <div class="card">
      <%= image_tag 'food', alt:"character", width: '100%', height: '200' %>
      <div class="card-body">
        <h5 class="card-title">食べ物について</h5>
        <p class="card-text">普段意識することはあまりないと思いますが、食べ物には食べやすいもの・食べにくいものがあります。<br>この２種類を具体的に紹介します。</p>
        <%= link_to "Go to Next Page!", food_path, class:"btn btn-primary"%>
      </div>
    </div>
    <div class="card">
      <%= image_tag 'toromi', alt:"character", width: '100%', height: '200' %>
      <div class="card-body">
        <h5 class="card-title">とろみって何？</h5>
        <p class="card-text">液体は、飲み込みの能力が落ちている人にとって飲み込みにくいものです。<br>飲み込みにくさを解消させる「トロミ」というものを詳しく説明します。</p>
        <%= link_to "Go to Next Page!", toromi_path, class:"btn btn-primary"%>
      </div>
    </div>
    <div class="card">
      <%= image_tag 'quiz', alt:"character", width: '100%', height: '200' %>
      <div class="card-body">
        <h5 class="card-title">クイズ！</h5>
        <p class="card-text">現場で出会いそうなケースをクイズにしてみました！<br>「私ならこう考える」という視点で書いているため、必ずしも正解ではないものもあります。「自分ならどうするか？」を色々考えてみてください！</p>
        <%= link_to "Go to Next Page!", quiz_path, class:"btn btn-primary"%>
      </div>
    </div>
  </div>
</div>

app/views/introduce/index.html.erb
<%= render partial: 'modules/header' %>
<body class="introduce__container">
  <div class="container">  
    <div class="accordion" id="accordionExample">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              このサイトについて
            </button>
          </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body">
          このサイトは嚥下障害のある方・家族・これからその様な方に接していくであろう人に見ていただきたく作成しました。<br>
          言語聴覚士として現場で働いていた際に、働く人たちや家族様に知っておいて欲しいかったことを書いております。<br>
          できるだけわかりやすく説明しようとは思いますが解剖のことも一部必要なため、専門用語が時々入ります。（専門用語は出てきた際に説明を入れるつもりです）<br>
          本当は色々、おすすめの介護用品等あるのですが、著作権的に不明のため掲載しておりません。（載せたい…）
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingTwo">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              制作者自己紹介
            </button>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
          <div class="card-body">
          ・言語聴覚士歴４年<br>
          ・普通の４年生大学卒業後に医療業界に興味を持ち、専門学校に２年通う<br>
          ・現在はプログラミングスクール通い、プログラマーを目指している
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingThree">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              この仕事の中で思ったことなど
            </button>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
          <div class="card-body">
          専門学校に通っている時は、全く嚥下について興味はありませんでした。<br>
          入職当初はむしろ、飲み込みのリハビリはリスクが高すぎて嫌いなくらいでした。<br>
          しかし嚥下のリハビリをしていく中で、口から食べることができる様になったり、本人の希望に寄り添い、最期まで少しでも何かを食べることができたりした時は、「この仕事をやっていて良かった」と思いました。<br>
          色々な経験をして徐々に苦手意識は薄れていきましたが、食事介助が「人の命を奪いかねないという行為であること」に対しても意識が薄くなっていく自分に危機感を覚えることもありました。<br>
          私は「危機感がなくなっていくこと」や「そもそもの知識不足」により、事故の起こる可能性は高くなると考えています。<br>
          防ぐことができる事故がなくなることに、このサイトが一助となれれば幸いです。<br>
          （頑張って情報随時追加します！）
          </div>
        </div>
      </div>
    </div>
    <%= link_to "ホームに戻る", home_path, class:"btn btn-primary"%>

  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SwallowingWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/modules/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3" >
  <%= link_to "Swallowing World", home_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", home_path, class: "nav-link"%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Contents
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "自己紹介", introduce_path, class: "dropdown-item" %>
          <%= link_to "嚥下とは？", swallowing_path, class: "dropdown-item" %>
          <%= link_to "誤嚥とは？", aspiration_path, class: "dropdown-item" %>
          <%= link_to "食べ物について", food_path, class: "dropdown-item" %>
          <%= link_to "とろみって何？", toromi_path, class: "dropdown-item" %>
          <%= link_to "クイズ！", quiz_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>